/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bicycle_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[12] = {3, 6, 0, 0, 0, 0, 1, 2, 3, 1, 0, 2};
static const casadi_int casadi_s1[9] = {6, 3, 0, 1, 2, 3, 4, 3, 5};
static const casadi_int casadi_s2[18] = {6, 3, 0, 4, 8, 12, 0, 1, 2, 4, 0, 1, 2, 3, 0, 1, 2, 5};
static const casadi_int casadi_s3[15] = {6, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[24] = {6, 3, 0, 6, 12, 18, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s8[222] = {218, 1, 0, 218, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217};
static const casadi_int casadi_s9[27] = {6, 6, 0, 3, 6, 9, 12, 15, 18, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* bicycle_model_expl_vde_forw:(i0[6],i1[6x6],i2[6x3],i3[3],i4[218])->(o0[6],o1[6x6,18nz],o2[6x3,12nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, *w7=w+13, *w8=w+49, *w9=w+55, *w10=w+61, *w11=w+67, *w12=w+73, *w13=w+79, w14, w15, w16, w17, w18, *w19=w+90, *w21=w+93, *w22=w+96, *w23=w+99, *w24=w+111, *w25=w+129, *w26=w+138;
  /* #0: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #5: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #6: @3 = (@0*@1) */
  w3  = (w0*w1);
  /* #7: output[0][1] = @3 */
  if (res[0]) res[0][1] = w3;
  /* #8: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #9: @4 = tan(@3) */
  w4 = tan( w3 );
  /* #10: @5 = (@0*@4) */
  w5  = (w0*w4);
  /* #11: @6 = 1.5 */
  w6 = 1.5000000000000000e+00;
  /* #12: @5 = (@5/@6) */
  w5 /= w6;
  /* #13: output[0][2] = @5 */
  if (res[0]) res[0][2] = w5;
  /* #14: @5 = input[3][1] */
  w5 = arg[3] ? arg[3][1] : 0;
  /* #15: output[0][3] = @5 */
  if (res[0]) res[0][3] = w5;
  /* #16: @5 = 0.2032 */
  w5 = 2.0319999999999999e-01;
  /* #17: @6 = input[3][0] */
  w6 = arg[3] ? arg[3][0] : 0;
  /* #18: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #19: output[0][4] = @6 */
  if (res[0]) res[0][4] = w6;
  /* #20: @6 = input[3][2] */
  w6 = arg[3] ? arg[3][2] : 0;
  /* #21: output[0][5] = @6 */
  if (res[0]) res[0][5] = w6;
  /* #22: @7 = input[1][0] */
  casadi_copy(arg[1], 36, w7);
  /* #23: {@8, @9, @10, @11, @12, @13} = horzsplit(@7) */
  casadi_copy(w7, 6, w8);
  casadi_copy(w7+6, 6, w9);
  casadi_copy(w7+12, 6, w10);
  casadi_copy(w7+18, 6, w11);
  casadi_copy(w7+24, 6, w12);
  casadi_copy(w7+30, 6, w13);
  /* #24: {NULL, NULL, @6, @14, @15, NULL} = vertsplit(@8) */
  w6 = w8[2];
  w14 = w8[3];
  w15 = w8[4];
  /* #25: @16 = (@2*@15) */
  w16  = (w2*w15);
  /* #26: @17 = (@1*@6) */
  w17  = (w1*w6);
  /* #27: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #28: @16 = (@16-@17) */
  w16 -= w17;
  /* #29: output[1][0] = @16 */
  if (res[1]) res[1][0] = w16;
  /* #30: @16 = (@1*@15) */
  w16  = (w1*w15);
  /* #31: @6 = (@2*@6) */
  w6  = (w2*w6);
  /* #32: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #33: @16 = (@16+@6) */
  w16 += w6;
  /* #34: output[1][1] = @16 */
  if (res[1]) res[1][1] = w16;
  /* #35: @16 = 0.666667 */
  w16 = 6.6666666666666663e-01;
  /* #36: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #37: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #38: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #39: @14 = (@14/@3) */
  w14 /= w3;
  /* #40: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #41: @15 = (@15+@14) */
  w15 += w14;
  /* #42: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #43: output[1][2] = @15 */
  if (res[1]) res[1][2] = w15;
  /* #44: {NULL, NULL, @15, @14, @6, NULL} = vertsplit(@9) */
  w15 = w9[2];
  w14 = w9[3];
  w6 = w9[4];
  /* #45: @17 = (@2*@6) */
  w17  = (w2*w6);
  /* #46: @18 = (@1*@15) */
  w18  = (w1*w15);
  /* #47: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #48: @17 = (@17-@18) */
  w17 -= w18;
  /* #49: output[1][3] = @17 */
  if (res[1]) res[1][3] = w17;
  /* #50: @17 = (@1*@6) */
  w17  = (w1*w6);
  /* #51: @15 = (@2*@15) */
  w15  = (w2*w15);
  /* #52: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #53: @17 = (@17+@15) */
  w17 += w15;
  /* #54: output[1][4] = @17 */
  if (res[1]) res[1][4] = w17;
  /* #55: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #56: @14 = (@14/@3) */
  w14 /= w3;
  /* #57: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #58: @6 = (@6+@14) */
  w6 += w14;
  /* #59: @6 = (@16*@6) */
  w6  = (w16*w6);
  /* #60: output[1][5] = @6 */
  if (res[1]) res[1][5] = w6;
  /* #61: {NULL, NULL, @6, @14, @17, NULL} = vertsplit(@10) */
  w6 = w10[2];
  w14 = w10[3];
  w17 = w10[4];
  /* #62: @15 = (@2*@17) */
  w15  = (w2*w17);
  /* #63: @18 = (@1*@6) */
  w18  = (w1*w6);
  /* #64: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #65: @15 = (@15-@18) */
  w15 -= w18;
  /* #66: output[1][6] = @15 */
  if (res[1]) res[1][6] = w15;
  /* #67: @15 = (@1*@17) */
  w15  = (w1*w17);
  /* #68: @6 = (@2*@6) */
  w6  = (w2*w6);
  /* #69: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #70: @15 = (@15+@6) */
  w15 += w6;
  /* #71: output[1][7] = @15 */
  if (res[1]) res[1][7] = w15;
  /* #72: @17 = (@4*@17) */
  w17  = (w4*w17);
  /* #73: @14 = (@14/@3) */
  w14 /= w3;
  /* #74: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #75: @17 = (@17+@14) */
  w17 += w14;
  /* #76: @17 = (@16*@17) */
  w17  = (w16*w17);
  /* #77: output[1][8] = @17 */
  if (res[1]) res[1][8] = w17;
  /* #78: {NULL, NULL, @17, @14, @15, NULL} = vertsplit(@11) */
  w17 = w11[2];
  w14 = w11[3];
  w15 = w11[4];
  /* #79: @6 = (@2*@15) */
  w6  = (w2*w15);
  /* #80: @18 = (@1*@17) */
  w18  = (w1*w17);
  /* #81: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #82: @6 = (@6-@18) */
  w6 -= w18;
  /* #83: output[1][9] = @6 */
  if (res[1]) res[1][9] = w6;
  /* #84: @6 = (@1*@15) */
  w6  = (w1*w15);
  /* #85: @17 = (@2*@17) */
  w17  = (w2*w17);
  /* #86: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #87: @6 = (@6+@17) */
  w6 += w17;
  /* #88: output[1][10] = @6 */
  if (res[1]) res[1][10] = w6;
  /* #89: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #90: @14 = (@14/@3) */
  w14 /= w3;
  /* #91: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #92: @15 = (@15+@14) */
  w15 += w14;
  /* #93: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #94: output[1][11] = @15 */
  if (res[1]) res[1][11] = w15;
  /* #95: {NULL, NULL, @15, @14, @6, NULL} = vertsplit(@12) */
  w15 = w12[2];
  w14 = w12[3];
  w6 = w12[4];
  /* #96: @17 = (@2*@6) */
  w17  = (w2*w6);
  /* #97: @18 = (@1*@15) */
  w18  = (w1*w15);
  /* #98: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #99: @17 = (@17-@18) */
  w17 -= w18;
  /* #100: output[1][12] = @17 */
  if (res[1]) res[1][12] = w17;
  /* #101: @17 = (@1*@6) */
  w17  = (w1*w6);
  /* #102: @15 = (@2*@15) */
  w15  = (w2*w15);
  /* #103: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #104: @17 = (@17+@15) */
  w17 += w15;
  /* #105: output[1][13] = @17 */
  if (res[1]) res[1][13] = w17;
  /* #106: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #107: @14 = (@14/@3) */
  w14 /= w3;
  /* #108: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #109: @6 = (@6+@14) */
  w6 += w14;
  /* #110: @6 = (@16*@6) */
  w6  = (w16*w6);
  /* #111: output[1][14] = @6 */
  if (res[1]) res[1][14] = w6;
  /* #112: {NULL, NULL, @6, @14, @17, NULL} = vertsplit(@13) */
  w6 = w13[2];
  w14 = w13[3];
  w17 = w13[4];
  /* #113: @15 = (@2*@17) */
  w15  = (w2*w17);
  /* #114: @18 = (@1*@6) */
  w18  = (w1*w6);
  /* #115: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #116: @15 = (@15-@18) */
  w15 -= w18;
  /* #117: output[1][15] = @15 */
  if (res[1]) res[1][15] = w15;
  /* #118: @15 = (@1*@17) */
  w15  = (w1*w17);
  /* #119: @6 = (@2*@6) */
  w6  = (w2*w6);
  /* #120: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #121: @15 = (@15+@6) */
  w15 += w6;
  /* #122: output[1][16] = @15 */
  if (res[1]) res[1][16] = w15;
  /* #123: @17 = (@4*@17) */
  w17  = (w4*w17);
  /* #124: @14 = (@14/@3) */
  w14 /= w3;
  /* #125: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #126: @17 = (@17+@14) */
  w17 += w14;
  /* #127: @17 = (@16*@17) */
  w17  = (w16*w17);
  /* #128: output[1][17] = @17 */
  if (res[1]) res[1][17] = w17;
  /* #129: @19 = zeros(3x6,3nz) */
  casadi_clear(w19, 3);
  /* #130: @20 = 00 */
  /* #131: @21 = ones(3x1) */
  casadi_fill(w21, 3, 1.);
  /* #132: {@17, @14, @15} = vertsplit(@21) */
  w17 = w21[0];
  w14 = w21[1];
  w15 = w21[2];
  /* #133: @5 = (@5*@17) */
  w5 *= w17;
  /* #134: @21 = vertcat(@20, @20, @20, @14, @5, @15) */
  rr=w21;
  *rr++ = w14;
  *rr++ = w5;
  *rr++ = w15;
  /* #135: @22 = @21[:3] */
  for (rr=w22, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #136: (@19[:3] = @22) */
  for (rr=w19+0, ss=w22; rr!=w19+3; rr+=1) *rr = *ss++;
  /* #137: @22 = @19' */
  casadi_trans(w19,casadi_s0, w22, casadi_s1, iw);
  /* #138: @23 = project(@22) */
  casadi_project(w22, casadi_s1, w23, casadi_s2, w);
  /* #139: @24 = input[2][0] */
  casadi_copy(arg[2], 18, w24);
  /* #140: {@13, @12, @11} = horzsplit(@24) */
  casadi_copy(w24, 6, w13);
  casadi_copy(w24+6, 6, w12);
  casadi_copy(w24+12, 6, w11);
  /* #141: {NULL, NULL, @14, @5, @15, NULL} = vertsplit(@13) */
  w14 = w13[2];
  w5 = w13[3];
  w15 = w13[4];
  /* #142: @17 = (@2*@15) */
  w17  = (w2*w15);
  /* #143: @6 = (@1*@14) */
  w6  = (w1*w14);
  /* #144: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #145: @17 = (@17-@6) */
  w17 -= w6;
  /* #146: @6 = (@1*@15) */
  w6  = (w1*w15);
  /* #147: @14 = (@2*@14) */
  w14  = (w2*w14);
  /* #148: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #149: @6 = (@6+@14) */
  w6 += w14;
  /* #150: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #151: @5 = (@5/@3) */
  w5 /= w3;
  /* #152: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #153: @15 = (@15+@5) */
  w15 += w5;
  /* #154: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #155: @22 = vertcat(@17, @6, @15, @20, @20, @20) */
  rr=w22;
  *rr++ = w17;
  *rr++ = w6;
  *rr++ = w15;
  /* #156: {NULL, NULL, @17, @6, @15, NULL} = vertsplit(@12) */
  w17 = w12[2];
  w6 = w12[3];
  w15 = w12[4];
  /* #157: @5 = (@2*@15) */
  w5  = (w2*w15);
  /* #158: @14 = (@1*@17) */
  w14  = (w1*w17);
  /* #159: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #160: @5 = (@5-@14) */
  w5 -= w14;
  /* #161: @14 = (@1*@15) */
  w14  = (w1*w15);
  /* #162: @17 = (@2*@17) */
  w17  = (w2*w17);
  /* #163: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #164: @14 = (@14+@17) */
  w14 += w17;
  /* #165: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #166: @6 = (@6/@3) */
  w6 /= w3;
  /* #167: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #168: @15 = (@15+@6) */
  w15 += w6;
  /* #169: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #170: @19 = vertcat(@5, @14, @15, @20, @20, @20) */
  rr=w19;
  *rr++ = w5;
  *rr++ = w14;
  *rr++ = w15;
  /* #171: {NULL, NULL, @5, @14, @15, NULL} = vertsplit(@11) */
  w5 = w11[2];
  w14 = w11[3];
  w15 = w11[4];
  /* #172: @6 = (@2*@15) */
  w6  = (w2*w15);
  /* #173: @17 = (@1*@5) */
  w17  = (w1*w5);
  /* #174: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #175: @6 = (@6-@17) */
  w6 -= w17;
  /* #176: @1 = (@1*@15) */
  w1 *= w15;
  /* #177: @2 = (@2*@5) */
  w2 *= w5;
  /* #178: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #179: @1 = (@1+@2) */
  w1 += w2;
  /* #180: @4 = (@4*@15) */
  w4 *= w15;
  /* #181: @14 = (@14/@3) */
  w14 /= w3;
  /* #182: @0 = (@0*@14) */
  w0 *= w14;
  /* #183: @4 = (@4+@0) */
  w4 += w0;
  /* #184: @16 = (@16*@4) */
  w16 *= w4;
  /* #185: @21 = vertcat(@6, @1, @16, @20, @20, @20) */
  rr=w21;
  *rr++ = w6;
  *rr++ = w1;
  *rr++ = w16;
  /* #186: @25 = horzcat(@22, @19, @21) */
  rr=w25;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #187: @26 = project(@25) */
  casadi_project(w25, casadi_s3, w26, casadi_s2, w);
  /* #188: @23 = (@23+@26) */
  for (i=0, rr=w23, cs=w26; i<12; ++i) (*rr++) += (*cs++);
  /* #189: output[2][0] = @23 */
  casadi_copy(w23, 12, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real bicycle_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 150;
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 4*sizeof(casadi_int);
  if (sz_w) *sz_w = 150*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
