/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bicycle_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[222] = {218, 1, 0, 218, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217};
static const casadi_int casadi_s3[10] = {9, 1, 0, 6, 2, 3, 4, 6, 7, 8};

/* bicycle_model_expl_vde_adj:(i0[6],i1[6],i2[3],i3[218])->(o0[9x1,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, *w3=w+3, w4, w5, w6, w7, w8, w9, w10, w11;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[0][4] */
  w2 = arg[0] ? arg[0][4] : 0;
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 6, w3);
  /* #4: {@4, @5, @6, @7, @8, @9} = vertsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  w8 = w3[4];
  w9 = w3[5];
  /* #5: @10 = (@2*@5) */
  w10  = (w2*w5);
  /* #6: @10 = (@1*@10) */
  w10  = (w1*w10);
  /* #7: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #8: @11 = (@2*@4) */
  w11  = (w2*w4);
  /* #9: @11 = (@0*@11) */
  w11  = (w0*w11);
  /* #10: @10 = (@10-@11) */
  w10 -= w11;
  /* #11: output[0][0] = @10 */
  if (res[0]) res[0][0] = w10;
  /* #12: @10 = 0.666667 */
  w10 = 6.6666666666666663e-01;
  /* #13: @10 = (@10*@6) */
  w10 *= w6;
  /* #14: @2 = (@2*@10) */
  w2 *= w10;
  /* #15: @6 = input[0][3] */
  w6 = arg[0] ? arg[0][3] : 0;
  /* #16: @11 = cos(@6) */
  w11 = cos( w6 );
  /* #17: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #18: @2 = (@2/@11) */
  w2 /= w11;
  /* #19: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #20: @6 = tan(@6) */
  w6 = tan( w6 );
  /* #21: @6 = (@6*@10) */
  w6 *= w10;
  /* #22: @0 = (@0*@5) */
  w0 *= w5;
  /* #23: @6 = (@6+@0) */
  w6 += w0;
  /* #24: @1 = (@1*@4) */
  w1 *= w4;
  /* #25: @6 = (@6+@1) */
  w6 += w1;
  /* #26: output[0][2] = @6 */
  if (res[0]) res[0][2] = w6;
  /* #27: @6 = 0.2032 */
  w6 = 2.0319999999999999e-01;
  /* #28: @6 = (@6*@8) */
  w6 *= w8;
  /* #29: output[0][3] = @6 */
  if (res[0]) res[0][3] = w6;
  /* #30: output[0][4] = @7 */
  if (res[0]) res[0][4] = w7;
  /* #31: output[0][5] = @9 */
  if (res[0]) res[0][5] = w9;
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bicycle_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 17;
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 17*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
